easy_admin:
    design:
        menu:
            - { label: menu.main }
            - { entity: Area, icon: 'map-marker', label: entity.area.list }
            - { entity: Tournament, icon: 'dot-circle-o', label: entity.tournament.list }
            - { entity: TournamentSeason, icon: 'calendar-check-o', label: entity.season.list }
            - { entity: User, icon: 'users', label: entity.user.list }

            - { label: menu.finance }
            - { entity: TournamentWithoutLicense, icon: 'exclamation-triangle', label: entity.tournamentWithoutLicense.list }

            - { label: menu.content }
            - { entity: Info, icon: 'info', label: entity.info.list}
            - { entity: PartnerPage, icon: 'database', label: entity.partnerPage.list}
            - { entity: Advert, icon: 'file-text', label: entity.advert.list}
            - { entity: Review, icon: 'heart', label: entity.review.list}
            - { entity: ReviewWithoutApproval, icon: 'heart-o', label: entity.reviewWithoutApproval.list}