easy_admin:
    formats:
        number: '%01.0f'
    entities:
        TournamentSeason:
            class: AppBundle\Entity\TournamentSeason
            label: entity.season.title
            list:
                title: entity.season.list
                sort: 'year'
                fields:
                    - year
                    - title
                    - tournament
            form:
                title: entity.area.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: 'form.general', icon: 'info' }
                    - title
                    - year
                    - tournament